// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJy_rjG48_s1jAsIqw1b0lmNPiJbcbYs',
    appId: '1:242613738229:web:ffd2bf4640bc4ea17943bc',
    messagingSenderId: '242613738229',
    projectId: 'reminder-yeepeng',
    authDomain: 'reminder-yeepeng.firebaseapp.com',
    databaseURL: 'https://reminder-yeepeng-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-yeepeng.firebasestorage.app',
    measurementId: 'G-VDFTQ2RN3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMK-xLOUOJXO5LRytn8ENrdJ56bDdHvE',
    appId: '1:242613738229:android:34cc75998a01b6b87943bc',
    messagingSenderId: '242613738229',
    projectId: 'reminder-yeepeng',
    databaseURL: 'https://reminder-yeepeng-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-yeepeng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AOwtkbXHLdWjainRGszaw39CbWbh9gw',
    appId: '1:242613738229:ios:3b5cc677cb798e497943bc',
    messagingSenderId: '242613738229',
    projectId: 'reminder-yeepeng',
    databaseURL: 'https://reminder-yeepeng-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-yeepeng.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-AOwtkbXHLdWjainRGszaw39CbWbh9gw',
    appId: '1:242613738229:ios:3b5cc677cb798e497943bc',
    messagingSenderId: '242613738229',
    projectId: 'reminder-yeepeng',
    databaseURL: 'https://reminder-yeepeng-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-yeepeng.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWJy_rjG48_s1jAsIqw1b0lmNPiJbcbYs',
    appId: '1:242613738229:web:75ff6cbae30be9397943bc',
    messagingSenderId: '242613738229',
    projectId: 'reminder-yeepeng',
    authDomain: 'reminder-yeepeng.firebaseapp.com',
    databaseURL: 'https://reminder-yeepeng-default-rtdb.firebaseio.com',
    storageBucket: 'reminder-yeepeng.firebasestorage.app',
    measurementId: 'G-MEPZJNGHY5',
  );

}